path: data/coco/images
train_dir: data/coco/a6/train
validation_dir: data/coco/a6/test
project: cell_segmentation_a6
version: 0_test
hyperparameters:
    in_channels: 3
    pyramid_channels: 64
    depth: 5
    num_classes: 2
    lr0: 0.001
